---
grafana:
  service:
    type: LoadBalancer

  ingress:
    enabled: true
    hosts:
    - grafana.k8s.milkyway.home.navaulakh.com

prometheus:
  service:
    type: LoadBalancer
    
  ingress:
    enabled: true
    hosts:
    - prometheus.k8s.milkyway.home.navaulakh.com

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  
