---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: helloworld
  labels:
    app: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      name: helloworld-pod
      namespace: helloworld
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld-container
          image: navi/helloworld:latest
          resources:
            limits:
              memory: "250Mi"
            requests:
              memory: "250Mi"
          command: ["/venv/bin/uvicorn"]
          args: [
            "main:app",
            "--host",
            "0.0.0.0"
          ]

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: helloworld
  labels:
    app: helloworld
spec:
  selector:
    app: helloworld
  ports:
    - name: http-helloworld
      protocol: TCP
      port: 80
      targetPort: 8000
      
    
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: helloworld-ingress
  namespace: helloworld
  labels:
    app: helloworld
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: helloworld.k8s.milkyway.home.navaulakh.com
      http:
        paths:
          - path: /
            backend:
              serviceName: helloworld-service
              servicePort: 80


# Prometheus stuff
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helloworld-servicemonitor
  namespace: helloworld
  labels:
    env: development
spec:
  selector:
    matchLabels:
      app: helloworld
  namespaceSelector:
    matchNames:
    - helloworld
  endpoints:
  - port: http-helloworld
