---
- name: Add Docker apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker

- name: Install Docker dependencies
  become: yes
  apt:
    name: [
      "aptitude",
      "apt-transport-https",
      "ca-certificates",
      "curl",
      "software-properties-common",
    ]
    update_cache: yes

- name: Install Docker-CE
  become: yes
  apt:
    name: "docker-ce"
    state: latest
    update_cache: yes

- name: Add user to docker group
  become: yes
  user: 
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Install docker-compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ binary_path }}/docker-compose"
    mode: 0755